# condor/run.py configs/tempeh/train_tempeh.yaml
# condor/submit.py configs/tempeh/train_tempeh.yaml 25

name: tempeh_selftrained
out_dir: experiments/tempeh/
script: scripts/tempeh/train_tempeh.py
arguments: "--model-directory ${out_dir} \
            --experiment-id ${name} \
            --num-iterations 2000000 \
            --dataset-directory data/ava-256 \ 
            --camera-angles '[[0,0], [0, -15], [20,0], [20, 36], [20, -15], [-20,0], [-20, 36], [-20, -15], [40,-5], [40, 25], [-40,-5], [-40, 25]]' \
            --height 256 \
            --width 167 \
            --frame-stride 10"

# condor configs
CondorParameters:
  name: ${name}
  batch_name: ${name}
  cmd: 'python ${script} ${arguments}'
  requirements: '(TARGET.CUDACapability >= 8.0)'
  base_dir: ${out_dir}
  request_gpus: 1
  request_cpus: 32
  request_memory: 128_000
  request_disk: 50G
  backup_root: null
  backup_excludepatterns: ['third_party']
  environment: {'CC': 'gcc-11', 'CXX':'g++-11'}
  njobs: 1
  retries: 0